# Default configuration for the classification task (Transformer on AG News)
task: "cls"
activation: "relu"

learning_rate: 5e-5
batch_size: 32
max_epochs: 5
warmup_steps: 100
adamw_weight_decay: 0.01
